os: linux
dist: trusty 
sudo: false
language: java
jdk: oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn test -DoutputFormats=XML org.pitest:pitest-maven:mutationCoverage
after_success:
    - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: flaviobeck:U6kilEKFzgEH1EYC9JyM0goD
deploy:
  provider: releases
  api_key: $GH_TOKEN
  github_token: $GH_TOKEN
  file_glob: true
  file: target/pit-reports/**/*
  overwrite: true
  skip_cleanup: true
  on:
    tag: true
  