language: java

sudo: false

jdk:
  - oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

os:
  - linux
  
dist: trusty 

addons:
  sonarcloud:
    organization: "flaviobeck"
    token:
      secure: "1ddf995ecc1488d34589454379efbdd0df5dbf2e"

script: 
    #- mvn cobertura:cobertura
    - mvn test -DoutputFormats=XML org.pitest:pitest-maven:mutationCoverage
    #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=flaviobeck_persian-date-time

after_success:
    - bash <(curl -s https://codecov.io/bash)
    
