os: linux
  
dist: trusty 

sudo: false

language: java

jdk: oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
    #- mvn test -DoutputFormats=XML org.pitest:pitest-maven:mutationCoverage
    - mvn deploy -Dregistry=https://maven.pkg.github.com/flaviobeck -Dtoken=GH_TOKEN

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: flaviobeck:U6kilEKFzgEH1EYC9JyM0goD
  
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache 

