os: linux
dist: trusty 
sudo: false
language: 
  - java
  - python
jdk: 
  - oraclejdk8
python:
  - "2.7"
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -DoutputFormats=XML org.pitest:pitest-maven:mutationCoverage
after_success:
  - pwd
  - ls
  - cd target
  - ls
  - cd pit-reports
  - ls
  - cd $(ls -d */|head -n 1)
  - ls
  - cp *.xml ../../
  - cd ../../../
  - pwd
  - ls
  - python parsing.py
notifications:
  slack: flaviobeck:U6kilEKFzgEH1EYC9JyM0goD

before_deploy:
  - git config --local user.name "flaviobeck"
  - git config --local user.email "flaviobeck@yahoo.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  github_token: $GH_TOKEN
  file_glob: true
  file: 
    - target/pit-reports/**/*
    - target/mutation_parsed.xml
  overwrite: true
  skip_cleanup: true
  on:
    branch: travis	
    tag: true
  