language: java

sudo: false

jdk:
  - oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

os:
  - linux
  
dist: trusty 

script: "mvn cobertura:cobertura"

after_success:
    - bash <(curl -s https://codecov.io/bash)
